### ISSUE TITLE
dsc_registry generates InDesiredState = $false which forces to set entries on every puppet run

### ISSUE THREAD

**Issue by marcinbojko** [PowerShell/DscResources#203]
1. Description
Setting any value in registry returns notify every time puppet agent launches. Dsc_registry returns " InDesiredState = $false" despite values being written correctly.

2. Values for module:
```
tightvncpassword:
  dsc_key: HKEY_LOCAL_MACHINE\SOFTWARE\TightVNC\Server
  dsc_valuename: Password
  dsc_hex: true
  dsc_valuedata: 00 00 00 00 00 00 00
  dsc_valuetype: binary
```
3. How to reproduce:
use dsc_registry with values above.

4. More data: https://github.com/puppetlabs/puppetlabs-dsc/issues/237
