### ISSUE TITLE
Update AppVeyor YAML template for resource modules

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#347]
I suggest we update the template for appveyor.yml at this location https://github.com/PowerShell/DscResources/blob/master/DscResource.Template/appveyor.yml with a more current one. 

I propose the below which uses the "default model"  and will run all the default common tests, with the option for the maintainer to opt-in for the rest of the test when so is possible.

```
#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 1.0.{build}.0
install:
    - git clone https://github.com/PowerShell/DscResource.Tests
    - ps: Write-Verbose -Message "PowerShell version $($PSVersionTable.PSVersion)" -Verbose
    - ps: Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
    - ps: Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask -CodeCoverage -CodeCovIo -ExcludeTag @()
#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
    - ps: |
        Invoke-AppveyorAfterTestTask
```
