### ISSUE TITLE
Add Stale to DSC Resource Kit repositories

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#401]
After testing [Stale](https://github.com/probot/stale) in my test repo [DebugApps](https://github.com/johlju/DebugApps) it seems to work very well for part of our workflow. I suggest we add this GitHub App to DSC Resource Kit.

It will not be enabled until each repo opt-in by adding the below configuration to `.github/stale.yml`. The below configuration will handle issues and pull request differently. *Each repository can set this individually.*

### Issues
It will remind that there haven't been activity on an issue for 30 days. If there are no further activity withing 40 days it will close the issue. It will not close an issue if the issue is assigned one of the labels under *exemptLabels* (the last two of them is only needed for DscResources repo). Neither will it close issues that are part of a milestone or project (that is just a precaution, because those issues should have a work label assigned too). Any other label, like a "waiting..."-label, 'needs more information', 'question' or 'discussion' label will be kept when the issue is labeled 'stale'.
If a comment (activity) is made on the issue the 'needs more information' label is removed.
See example: https://github.com/PowerShell/SqlServerDsc/issues/811

### Pull Request (PR)
PR's that are not labeled with 'needs review', 'on hold' or 'waiting for CLA pass' will be labeled as abandoned after 14 days of inactivity. Any other label, like a "waiting..."-label will be kept when the issue is labeled 'abandoned'. If activity is made on the abandoned PR the 'abandoned' label is removed.
See example: https://github.com/PowerShell/SqlServerDsc/pull/1045

>**Note:** Pull requests that are labeled as 'waiting for CLA pass' should be closed after 14 days. But his app cannot handle that.

### Configuration

```yml
# Configuration for probot-stale - https://github.com/probot/stale

limitPerRun: 30

pulls:
  daysUntilStale: 14
  daysUntilClose: false
  exemptProjects: true
  exemptMilestones: true
  staleLabel: abandoned
  exemptLabels:
    - needs review
    - on hold
    - waiting for CLA pass

  markComment: >
    Labeling this pull request (PR) as abandoned since it has gone 14 days or more
    since the last update. An abandoned PR can be continued by another contributor.
    The abandoned label will be removed if work on this PR is taken up again.

issues:
  daysUntilStale: 30
  daysUntilClose: 40
  exemptProjects: true
  exemptMilestones: true
  staleLabel: stale
  exemptLabels:
    - bug
    - enhancement
    - tests
    - documentation
    - resource proposal
    - on hold
    - new module submission
    - module proposal

  markComment: >
    This issue has been automatically marked as stale because
    it has not had activity from the community in the last 30 days. It will be
    closed if no further activity occurs within 10 days. If the issue is labelled
    with any of the work labels (e.g bug, enhancement, documentation, or tests)
    then the issue will not auto-close.

  closeComment: >
    This issue has been automatically closed because it is has not had activity
    from the community in the last 40 days.
```
